import sqlite3
dbase = sqlite3.connect("BS_DATABASE2.db")
cursor=dbase.cursor()

cursor.execute('''CREATE TABLE IF NOT EXISTS CUSTOMER
(C_ID INT PRIMARY KEY NOT NULL,
C_ACCNO INT NOT NULL,
C_NAME TEXT NOT NULL,
C_ADD TEXT NOT NULL,
C_GEN TEXT NOT NULL,
C_DOB DATE NOT NULL,
C_PHONE UNSIGNED BIG INT NOT NULL,
C_EMAIL TEXT NOT NULL,
C_PASS TEXT NOT NULL,
C_ACCBAL INT NOT NULL)''')

cursor.execute('''CREATE TABLE IF NOT EXISTS EMPLOYEE
(E_ID INT PRIMARY KEY NOT NULL,
E_NAME TEXT NOT NULL,
E_ADD TEXT NOT NULL,
E_GEN TEXT NOT NULL,
E_DOB DATE NOT NULL,
E_PHONE UNSIGNED BIG INT NOT NULL,
E_EMAIL TEXT NOT NULL,
E_PASS TEXT NOT NULL,
E_SAL REAL  NOT NULL,
E_DEPT TEXT NOT NULL,
E_DESIG TEXT NOT NULL,
E_HDATE DATE NOT NULL)''')

cursor.execute('''CREATE TABLE IF NOT EXISTS TRANSACTIONS
(TR_ID INT PRIMARY KEY NOT NULL,
C_ID INT,
E_ID INT,
FRM_ACC INT,
TO_ACC INT,
TR_TYPE TEXT NOT NULL,
AMT INT NOT NULL,
DT DATE NOT NULL,
TM TIME NOT NULL,
FOREIGN KEY(C_ID) REFERENCES CUSTOMER(C_ID),
FOREIGN KEY(E_ID) REFERENCES EMPLOYEE(E_ID))''')

cursor.execute('''CREATE TABLE IF NOT EXISTS LOAN
(L_ID INT PRIMARY KEY NOT NULL,
L_Type TEXT NOT NULL,
C_ID INT NOT NULL,
L_Time INT NOT NULL,
L_IntRate INT NOT NULL,
L_Amt INT NOT NULL,
Final_Amt INT NOT NULL,
FOREIGN KEY(C_ID) REFERENCES CUSTOMER(C_ID))''')

dbase.commit()